keycloak:
  clientId: master-realm
  clientSecret: 39d48509-f52a-441f-a0d9-695f6c8375ef
  password: 1111
  realm: master
  serverUrl: http://127.0.0.1:8080/auth
  username: root

logging:
  level:
    com:
      skcc:
        cloudz:
          zcp: DEBUG
    org:
      hibernate: DEBUG
      keycloak: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
        
kube:
  client:
    api:
      output:
        pretty: true
  server:
    apiserver:
      endpoint: https://169.56.69.242:23078
    
server:
  port: 8282
zcp:
  keycloak:
    realm: zcp
  kube:
    namespace: zcp-system